config/routes.rb
Rails.application.routes.draw do

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'pages/lyriclab'
  get 'pages/launch'
  get 'pages/how_it_works'
  get 'pages/about_us'
  get 'pages/handbook'
  get 'pages/faqs'
  get 'pages/partnerships'
  get 'pages/legal_terms'
  get 'pages/careers'
  get 'pages/events'
  get 'pages/testpage'
  get 'pages/testpage2'
  get 'pages/home'
  get 'pages/blurbarchive'

  get 'tagged' => 'posts#tagged', :as => 'tagged'

  get 'dash' => 'profiles#dash', :as => 'dash'

  devise_for :users, :controllers => { :registrations => 'user/registrations', :invitations => 'user/invitation', omniauth_callbacks: 'user/omniauth_callbacks'}

resources :archives

resources :posts do
  member do
    get "like", to: "posts#upvote"
    get "dislike", to: "posts#downvote"
  end
  
  resources :commentposts
end

  resources :campaigns do
      resources :lyrics 
      resources :arts


    get 'filter' => 'arts#tagged', :as => 'filter'
    get 'tagged' => 'lyrics#tagged', :as => 'tagged'

    
  end

resources :lyrics, only: [] do
      member do
        get "like", to: "lyrics#upvote"
        get "dislike", to: "lyrics#downvote"
      end

      resources :comments
    end



  resources :arts, only: [] do
    member do
      put "voteof1", to: "arts#voteof1"
      put "voteof2", to: "arts#voteof2"
      put "voteof3", to: "arts#voteof3"
      put "voteof4", to: "arts#voteof4"
      put "voteof5", to: "arts#voteof5"
    end

    resources :ratings
    resources :commentarts
  end

  resources :profiles do

    member do
      get :follow
      get :unfollow
    end
  
  end

  resources :products

  resources :homeinfo

  resources :videos
  resources :photos



  root 'campaigns#index'
  
  
end

app/models/lyric.rb
class Lyric < ActiveRecord::Base
	acts_as_votable
	#is_impressionable :counter_cache => true, :column_name => :counter_cache, :unique => :request_hash
	belongs_to :user
	has_many :comments
	acts_as_taggable_on :tags
	belongs_to :campaign

	 scope :by_tags, -> tags { where(:tags => tags) }
	 scope :by_campaign, -> campaign_id { where("camapign_id = ?", :campaign_id) }
	 scope :most_liked, order(:cached_votes_up => :desc)
	 scope :most_recent, order("created_at desc")
	 scope :chosen, -> { where(:chosen => true) }
	 
	
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
	
	before_action :tag_cloud, :only => [:index, :tagged]
	has_scope :by_tags
	has_scope :by_campaign, :using => [:campaign_id]
	load_and_authorize_resource :only => [:show, :edit, :update, :destroy]
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :add_points]
	before_action :set_campaign, except: [:upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show, :tagged]
	#impressionist :actions => [:show,:index], :unique => [:impressionable_type, :impressionable_id, :session_hash]
	before_action :add_points, only: [:upvote, :downvote]
	invisible_captcha only: [:create, :update], honeypot: :subtitle


	respond_to :html, :json, :js

	

	def index

		case params[:sort_by]
	      when 'most_liked'
	        @lyrics = apply_scopes(Lyric).all.order(:cached_votes_up => :desc).paginate(:page => params[:page], :per_page => 50)
	       when 'most_viewed'
	        @lyrics = apply_scopes(Lyric).all.order(:counter_cache => :desc).paginate(:page => params[:page], :per_page => 50)
	      when 'most_recent'
	        @lyrics = apply_scopes(Lyric).all.order("created_at DESC").paginate(:page => params[:page], :per_page => 50)
	      else
	        @lyrics = apply_scopes(Lyric).all.order("created_at DESC").paginate(:page => params[:page], :per_page => 50)
	    end

	end

	def show
		@comments = Comment.where(lyric_id: @lyric)
		@random_lyric = Lyric.where.not(id: @lyric).order("RANDOM()").first
		@random_lyrics = Lyric.where.not(id: @lyric).order("RANDOM()").take(5)

		if @lyric == Lyric.last
			@next_lyric = Lyric.order(id: :asc).first
		else
			@next_lyric = Lyric.where("id > ?", @lyric).order(id: :asc).first
		end

		if @lyric == Lyric.first
			@previous_lyric = Lyric.order(id: :asc).last
		else
			@previous_lyric = Lyric.where("id < ?", @lyric).order(id: :desc).first
		end
		
	end

	def new
		@lyric = Lyric.new
	end

	def create
		@lyric = Lyric.new(post_params)
		@lyric.user_id = current_user.id
		@lyric.campaign_id = @campaign.id

		if @lyric.save
			redirect_to([@lyric.campaign, @lyric])
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if @lyric.update(post_params)
			redirect_to([@lyric.campaign, @lyric])
		else
			render 'edit'
		end

	end

	def destroy
		@lyric.destroy
		redirect_to root_path
	end

	def upvote

		if user_signed_in?
		@lyric.upvote_by current_user

		 respond_to do |format|
    		format.html {redirect_to :back }
    		format.json { render json: { count: @lyric.cached_votes_up, count2: @lyric.cached_votes_down }}
    		format.js { render :layout => false }
    	end

    	else 
    		redirect_to login_path

   		end
    

	end

	def downvote
		if user_signed_in?
		@lyric.downvote_by current_user

		respond_to do |format|
    		format.html {redirect_to :back }
    		format.json { render json: {  count: @lyric.cached_votes_up, count2: @lyric.cached_votes_down } }
    		format.js { render :layout => false }
    	end

    	else 
    		redirect_to login_path

   		end
	end

	def add_points
		if user_signed_in?
		unless (current_user.voted_for? @lyric)

          @current_user.add_points(1, category: 'lyric')
        
      	end
      end
	end


	def tagged

  		if params[:tag].present? 
    		@lyrics = Lyric.tagged_with(params[:tag]).order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  		else 
    		@lyrics = apply_scopes(Lyric).all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)

  		end  
	end

	def tag_cloud
		
   		 @tags = Lyric.tag_counts_on(:tags)
  	end

  	 def all_following
		   @user = User.find_by_username(params[:username])
		   @users = User.find_by_username(params[:username]).all_following
		end

		def all_follows
		   @user = User.find_by_username(params[:username])
		   @users = User.find_by_username(params[:username]).followers
		end


	private


	def find_post
		@lyric = Lyric.find(params[:id])
	end

	def set_campaign
		@campaign = Campaign.find(params[:campaign_id])
	end


	def post_params
		params.require(:lyric).permit(:line, :description, :artist, :song, :album, :link, :tag_list, :chosen, :personal)
	end

end

app/helpers/lyrics_helper.rb
module LyricsHelper
	include ActsAsTaggableOn::TagsHelper
	
end

app/views/lyrics/edit.html.erb
<div class="addlyric">
 <h1>Edit Lyric</h1>

</div>

<%= render 'form' %>



<div class="formpage-footer">
<%= link_to 'Back', campaign_lyrics_path(@lyric.campaign), class: "back-button" %>

<%= link_to 'More Experiments', campaigns_path, class: "back-button" %>

</div>



<%= render 'layouts/footer' %>

app/views/lyrics/index.html.erb


<section class="main-section">

<section class="lyric-section">

<div class="works-top" id="works-exp2">
  <div class="how-campaign">
  <h2>Rhyme Center</h2>
  <p>This is where it goes down. The community chooses their favorite lyrics to inspire designs. The community then chooses their favorite designs to develop tees and products for the shop.</p>

<p>Vote on the lyrics below to help choose the lyrics that will inspire our next designs.</p>

  </div>

  <%= image_tag 'rhyme-image.png', :class => "how-image2" %>

  <div class="how-box2">
    <%= link_to 'How It Works', pages_how_it_works_path, :class => "" %>

  <%= link_to 'Lab Shop', 'http://shop.rhymesanddesigns.com/', :class => "" %>

  <%= link_to 'Add Lyric', new_campaign_lyric_path(Campaign.open.last), :class => "" %>


    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Sort
        <span class="caret"></span>
      </button>

      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><%= link_to 'Most Liked', :controller => 'lyrics', :sort_by => 'most_liked' %></li>
        <li role="presentation"><%= link_to 'Most Viewed', :controller => 'lyrics', :sort_by => 'most_viewed' %></li>
        <li role="presentation"><%= link_to 'Most Recent', :controller => 'lyrics', :sort_by => 'most_recent' %></li>
      </ul>
    </div>

    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Filter
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

         <% @tags.each do |tag| %>
              <% if tag.taggings_count > 4 %>
              <li role="presentation"><%= link_to tag.name, campaign_tagged_url(:tag => tag.name) %></li>
              <% end %>
          
            <% end %>
      </ul>
    </div>

  

  </div>

      <div class="how-box2-mobile">

    <%= link_to pages_how_it_works_path do %>
      <i class="fa fa-info"></i>
    <% end %>

    <%= link_to 'http://shop.rhymesanddesigns.com/' do %>
       <span class="glyphicon glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
    <% end %>

    <%= link_to new_campaign_lyric_path(Campaign.last) do %>
      <i class="fa fa-headphones"></i>
    <% end %>

    <div class="clear"></div>

        <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        <span class="glyphicon glyphicon glyphicon-sort" aria-hidden="true"></span>
        <span class="caret"></span>
      </button>

      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><%= link_to 'Most Liked', :controller => 'lyrics', :sort_by => 'most_liked' %></li>
        <li role="presentation"><%= link_to 'Most Viewed', :controller => 'lyrics', :sort_by => 'most_viewed' %></li>
        <li role="presentation"><%= link_to 'Most Recent', :controller => 'lyrics', :sort_by => 'most_recent' %></li>
      </ul>
    </div>

    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        <span class="glyphicon glyphicon glyphicon-filter" aria-hidden="true"></span>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

         <% @tags.each do |tag| %>
              <% if tag.taggings_count > 4 %>
              <li role="presentation"><%= link_to tag.name, campaign_tagged_url(:tag => tag.name) %></li>
              <% end %>
          
            <% end %>
      </ul>
    </div>



  </div>



  </div>

  <div id="lyrics">
    <% if @lyrics.any? %>
    <% @lyrics.each do |lyric| %>
    <div class="container-md">

        <% if lyric.line.present? %>
        <%= link_to Obscenity.replacement(:nonconsonants).sanitize(lyric.line), campaign_lyric_path(@campaign, lyric) %>

        <% end %>
        <ul>

          <% if user_signed_in? %>
          <li><span class="updown-button"><span class="up <%= lyric.id %>"><%= lyric.get_upvotes.size %> </span>
          <%= link_to like_lyric_path(lyric), class: ['voteup', lyric.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= lyric.id %>"><%= lyric.get_downvotes.size %></span>
          <%= link_to dislike_lyric_path(lyric), class: ['votedown', lyric.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>

          </li>

          <% else %>

          <li><span class="updown-button"><span class="up <%= lyric.id %>"><%= lyric.get_upvotes.size %> </span>
          <%= link_to_if user_signed_in?, like_lyric_path(lyric), class: ['voteup', lyric.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= lyric.id %>"><%= lyric.get_downvotes.size %></span>
          <%= link_to_if user_signed_in?, dislike_lyric_path(lyric), class: ['votedown', lyric.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>
        
          <span type="button" data-toggle="tooltip" data-placement="top" title="Sign In To Vote" class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
          </li>


          <% end %>
          <% if false %>
          <li><%= lyric.impressionist_count(:filter=>:session_hash) %> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></li>
          <% end %>


  <script>

    $('.voteup' + '.<%= lyric.id %>')
  .on('ajax:success', function (e, data, status, xhr) { 
    $('.up' + '.<%= lyric.id %>').html(data.count);
    $('.down' + '.<%= lyric.id %>').html(data.count2);
  });

    </script>

      <script>

    $('.votedown' + '.<%= lyric.id %>')
  .on('ajax:success', function (e, data, status, xhr) { 
    
    $('.down' + '.<%= lyric.id %>').html(data.count2);
    $('.up' + '.<%= lyric.id %>').html(data.count);
  });

    </script>

      
        <li><%= lyric.comments.count %> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></li>
        <li><% if lyric.user.avatar.present? %><%= image_tag lyric.user.avatar.url(:mini) %><% end %><% if lyric.user.username.present? %><%= link_to lyric.user.username, profile_url(:id => lyric.user.username) %><% end%></li>
       
        <% if lyric.personal == true %>
        <li><span data-toggle="tooltip" data-placement="top" title="Submitted By Artist"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></span></li>
       <% end %>

        </ul>
        <br />
        <% if lyric.tags.any? %>
        <ul class="tag-list">
        <li>
          <span class="glyphicon glyphicon glyphicon-tags" aria-hidden="true"></span>
          <% lyric.tags.each do |tag| %>
          <%= link_to tag.name, campaign_tagged_url(:tag => tag.name) %>
          <% end %></li>
        </ul>
        <% end %>
     
      
      </div>
    <% end %>

    <% else %>

      <div class="noposts"><h1>No Lyrics Posted Yet.</h1></div>

    <% end %>

    <div class="back-top" title="Top of Page"> <a href="#top" onclick="return false;"><i class="glyphicon glyphicon-chevron-up"></i></a></div> 

  </div>

  

 <br>
    <div class="paginate-box">
      <%= will_paginate @lyrics, renderer: BootstrapPagination::Rails %>
    </div>

    <%= render 'layouts/footer' %>

   
</section>


<section class="home-info">


  <div class="results"></div>
    

</section>



</section>






<script>
$(function(){


    // Enabling Popover Example 2 - JS (hidden content and title capturing)
    $(".popoverExampleTwo").popover({
        html : true, 
        content: function() {
          return $('.popoverExampleTwoHiddenContent').html();
        },
        title: function() {
          return $('.popoverExampleTwoHiddenTitle').html();
        }
    });
});

</script>

<script>
// fade in #back-top
$(function () {
    $(window).scroll(function () {
        if ($(this).scrollTop() > 500) {
            $('.back-top').fadeIn();
        } else {
            $('.back-top').fadeOut();
        }
    });

    // scroll body to 0px on click
    $('.back-top').click(function () {
        $('body,html').animate({
            scrollTop: 0
        }, 1600);
        return false;
    });
});
</script>

<script>

  $('.results').html("<%= j render(:partial => 'homeinfo/index') %>")

</script>

<script>
$(window).scroll(function () {
    var winTop = $(this).scrollTop(),
        winBottom = winTop + $(this).height(),
        left = $('.home-info'),
        leftBottom = left.height(),
        right = $('.lyric-section'),
        rightBottom = right.height();
    //when the user reached the bottom of '#leftShort' set its position to fixed 
    //to prevent it from moving on scroll 
    if (rightBottom <= leftBottom){


    } else{

          if (winBottom >= leftBottom) {
        left.css({
            'position': 'fixed',
            'bottom': '0px',
            
        });
    } else {
        //when the user scrolls back up revert its position to relative
        // to make it move up together with '#rightLong'
        left.css({
            'position': 'relative',
            'bottom': 'auto'

        });
    }

    }


});

</script>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>






app/views/lyrics/tagged.html.erb
<section class="main-section">

<section class="lyric-section">

<div class="works-top" id="works-exp2">
  <div class="how-campaign">
  <h2>Rhyme Center</h2>
  <p>This is where it goes down. The community chooses their favorite lyrics to inspire designs. The community then chooses their favorite designs to develop tees and products for the shop.</p>

<p>Vote on the lyrics below to help choose the lyrics that will inspire our next designs.</p>

  </div>

  <%= image_tag 'rhyme-image.png', :class => "how-image2" %>

  <div class="how-box2">
    <%= link_to 'How It Works', pages_how_it_works_path, :class => "" %>

  <%= link_to 'Lab Shop', 'http://shop.rhymesanddesigns.com/', :class => "" %>

  <%= link_to 'Add Lyric', new_campaign_lyric_path(Campaign.open.last), :class => "" %>


    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Sort
        <span class="caret"></span>
      </button>

      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><%= link_to 'Most Liked', :controller => 'lyrics', :sort_by => 'most_liked' %></li>
        <li role="presentation"><%= link_to 'Most Viewed', :controller => 'lyrics', :sort_by => 'most_viewed' %></li>
        <li role="presentation"><%= link_to 'Most Recent', :controller => 'lyrics', :sort_by => 'most_recent' %></li>
      </ul>
    </div>

    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Filter
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

         <% @tags.each do |tag| %>
              <% if tag.taggings_count > 4 %>
              <li role="presentation"><%= link_to tag.name, campaign_tagged_url(:tag => tag.name) %></li>
              <% end %>
          
            <% end %>
      </ul>
    </div>

  

  </div>

      <div class="how-box2-mobile">

    <%= link_to pages_how_it_works_path do %>
      <i class="fa fa-info"></i>
    <% end %>

    <%= link_to 'http://shop.rhymesanddesigns.com/' do %>
       <span class="glyphicon glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
    <% end %>

    <%= link_to new_campaign_lyric_path(Campaign.last) do %>
      <i class="fa fa-headphones"></i>
    <% end %>

    <div class="clear"></div>

        <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        <span class="glyphicon glyphicon glyphicon-sort" aria-hidden="true"></span>
        <span class="caret"></span>
      </button>

      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><%= link_to 'Most Liked', :controller => 'lyrics', :sort_by => 'most_liked' %></li>
        <li role="presentation"><%= link_to 'Most Viewed', :controller => 'lyrics', :sort_by => 'most_viewed' %></li>
        <li role="presentation"><%= link_to 'Most Recent', :controller => 'lyrics', :sort_by => 'most_recent' %></li>
      </ul>
    </div>

    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        <span class="glyphicon glyphicon glyphicon-filter" aria-hidden="true"></span>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

         <% @tags.each do |tag| %>
              <% if tag.taggings_count > 4 %>
              <li role="presentation"><%= link_to tag.name, campaign_tagged_url(:tag => tag.name) %></li>
              <% end %>
          
            <% end %>
      </ul>
    </div>



  </div>



  </div>

  <div id="lyrics">
    <% if @lyrics.any? %>
    <% @lyrics.each do |lyric| %>
    <div class="container-md">

        <% if lyric.line.present? %>
        <%= link_to Obscenity.replacement(:nonconsonants).sanitize(lyric.line), campaign_lyric_path(@campaign, lyric) %>

        <% end %>
        <ul>

          <% if user_signed_in? %>
          <li><span class="updown-button"><span class="up <%= lyric.id %>"><%= lyric.get_upvotes.size %> </span>
          <%= link_to like_lyric_path(lyric), class: ['voteup', lyric.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= lyric.id %>"><%= lyric.get_downvotes.size %></span>
          <%= link_to dislike_lyric_path(lyric), class: ['votedown', lyric.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>

          </li>

          <% else %>

          <li><span class="updown-button"><span class="up <%= lyric.id %>"><%= lyric.get_upvotes.size %> </span>
          <%= link_to_if user_signed_in?, like_lyric_path(lyric), class: ['voteup', lyric.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= lyric.id %>"><%= lyric.get_downvotes.size %></span>
          <%= link_to_if user_signed_in?, dislike_lyric_path(lyric), class: ['votedown', lyric.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>
        
          <span type="button" data-toggle="tooltip" data-placement="top" title="Sign In To Vote" class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
          </li>


          <% end %>

          <% if false %>
          <li><%= lyric.impressionist_count(:filter=>:session_hash) %> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></li>
          <% end %>


  <script>

    $('.voteup' + '.<%= lyric.id %>')
  .on('ajax:success', function (e, data, status, xhr) { 
    $('.up' + '.<%= lyric.id %>').html(data.count);
    $('.down' + '.<%= lyric.id %>').html(data.count2);
  });

    </script>

      <script>

    $('.votedown' + '.<%= lyric.id %>')
  .on('ajax:success', function (e, data, status, xhr) { 
    
    $('.down' + '.<%= lyric.id %>').html(data.count2);
    $('.up' + '.<%= lyric.id %>').html(data.count);
  });

    </script>

      
        <li><%= lyric.comments.count %> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></li>
        <li><% if lyric.user.avatar.present? %><%= image_tag lyric.user.avatar.url(:mini) %><% end %><% if lyric.user.username.present? %><%= link_to lyric.user.username, profile_url(:id => lyric.user.username) %><% end%></li>
       
        <% if lyric.personal == true %>
        <li><span data-toggle="tooltip" data-placement="top" title="Submitted By Artist"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></span></li>
       <% end %>

        </ul>
        <br />
        <% if lyric.tags.any? %>
        <ul class="tag-list">
        <li>
          <span class="glyphicon glyphicon glyphicon-tags" aria-hidden="true"></span>
          <% lyric.tags.each do |tag| %>
          <%= link_to tag.name, campaign_tagged_url(:tag => tag.name) %>
          <% end %></li>
        </ul>
        <% end %>
     
      
      </div>
    <% end %>

    <% else %>

      <div class="noposts"><h1>No Lyrics Posted Yet.</h1></div>

    <% end %>

    <div class="back-top" title="Top of Page"> <a href="#top" onclick="return false;"><i class="glyphicon glyphicon-chevron-up"></i></a></div> 

  </div>

  

 <br>
    <div class="paginate-box">
      <%= will_paginate @lyrics, renderer: BootstrapPagination::Rails %>
    </div>

    <%= render 'layouts/footer' %>

   
</section>


<section class="home-info">


  <div class="results"></div>
    

</section>



</section>






<script>
$(function(){


    // Enabling Popover Example 2 - JS (hidden content and title capturing)
    $(".popoverExampleTwo").popover({
        html : true, 
        content: function() {
          return $('.popoverExampleTwoHiddenContent').html();
        },
        title: function() {
          return $('.popoverExampleTwoHiddenTitle').html();
        }
    });
});

</script>

<script>
// fade in #back-top
$(function () {
    $(window).scroll(function () {
        if ($(this).scrollTop() > 500) {
            $('.back-top').fadeIn();
        } else {
            $('.back-top').fadeOut();
        }
    });

    // scroll body to 0px on click
    $('.back-top').click(function () {
        $('body,html').animate({
            scrollTop: 0
        }, 1600);
        return false;
    });
});
</script>

<script>

  $('.results').html("<%= j render(:partial => 'homeinfo/index') %>")

</script>

<script>
$(window).scroll(function () {
    var winTop = $(this).scrollTop(),
        winBottom = winTop + $(this).height(),
        left = $('.home-info'),
        leftBottom = left.height(),
        right = $('.lyric-section'),
        rightBottom = right.height();
    //when the user reached the bottom of '#leftShort' set its position to fixed 
    //to prevent it from moving on scroll 
    if (rightBottom <= leftBottom){


    } else{

          if (winBottom >= leftBottom) {
        left.css({
            'position': 'fixed',
            'bottom': '0px',
            
        });
    } else {
        //when the user scrolls back up revert its position to relative
        // to make it move up together with '#rightLong'
        left.css({
            'position': 'relative',
            'bottom': 'auto'

        });
    }

    }


});

</script>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>