config/routes.rb
Rails.application.routes.draw do

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'pages/lyriclab'
  get 'pages/launch'
  get 'pages/how_it_works'
  get 'pages/about_us'
  get 'pages/handbook'
  get 'pages/faqs'
  get 'pages/partnerships'
  get 'pages/legal_terms'
  get 'pages/careers'
  get 'pages/events'
  get 'pages/testpage'
  get 'pages/testpage2'
  get 'pages/home'
  get 'pages/blurbarchive'

  get 'tagged' => 'posts#tagged', :as => 'tagged'

  get 'dash' => 'profiles#dash', :as => 'dash'

  devise_for :users, :controllers => { :registrations => 'user/registrations', :invitations => 'user/invitation', omniauth_callbacks: 'user/omniauth_callbacks'}

resources :archives

resources :posts do
  member do
    get "like", to: "posts#upvote"
    get "dislike", to: "posts#downvote"
  end
  
  resources :commentposts
end

  resources :campaigns do
      resources :lyrics 
      resources :arts


    get 'filter' => 'arts#tagged', :as => 'filter'
    get 'tagged' => 'lyrics#tagged', :as => 'tagged'

    
  end

resources :lyrics, only: [] do
      member do
        get "like", to: "lyrics#upvote"
        get "dislike", to: "lyrics#downvote"
      end

      resources :comments
    end



  resources :arts, only: [] do
    member do
      put "voteof1", to: "arts#voteof1"
      put "voteof2", to: "arts#voteof2"
      put "voteof3", to: "arts#voteof3"
      put "voteof4", to: "arts#voteof4"
      put "voteof5", to: "arts#voteof5"
    end

    resources :ratings
    resources :commentarts
  end

  resources :profiles do

    member do
      get :follow
      get :unfollow
    end
  
  end

  resources :products

  resources :homeinfo

  resources :videos
  resources :photos



  root 'campaigns#index'
  
  
end

app/models/commentart.rb
class Commentart < ActiveRecord::Base
  belongs_to :art
  belongs_to :user
end

app/controllers/commentarts_controller.rb
class CommentartsController < ApplicationController
	before_action :authenticate_user!
	before_action :all_commentarts, only: [:create, :destroy]
	before_action :set_commentarts, only: [:destroy]
	respond_to :html, :js, :json

	def create
		@art = Art.find(params[:art_id])
		@commentart = Commentart.create(params[:commentart].permit(:content))
		@commentart.user_id = current_user.id
		@commentart.art_id = @art.id

		if @commentart.save

		respond_to do |format|
    		format.html {redirect_to([@art.campaign, @art])}
    		format.json
    		format.js
    	end
    	
		else
			render 'new'
		end
	end

	def destroy
	    @commentart.destroy
	    redirect_to :back
	  end

	private

		  def all_commentarts
	    	@art = Art.find(params[:art_id])
	    	@commentarts = Commentart.where(art_id: @art)
	    end

	   def set_commentarts

	      @commentart = Commentart.find(params[:id])
	    end

end

app/helpers/commentarts_helper.rb
module CommentartsHelper
end

app/views/commentarts/_commentart.html.erb
	<div class="comment">
		<% unless commentart.user.avatar.nil? %>
		<%= image_tag commentart.user.avatar.url(:mini) %>
		<% end %>
		<% unless commentart.user.username.nil? || commentart.user.username.empty? %>
		<p class="username"> <%= commentart.user.username %></p></br>
		<% end %>
		<% unless commentart.content.nil? || commentart.content.empty? %>
			<p class="content"> <%= commentart.content %></p>	
			<% end %>		
			<p class="time-created"><%= time_ago_in_words(commentart.created_at) %>
				<% if can? :destroy, commentart %>
				<%= link_to art_commentart_path(@art, commentart), class: "delete-link", method: :delete,  data: { confirm: 'Are you sure?' } do %>
				<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>

				<% end %>
				<% end %>

			</p>
				<hr />
	</div>

app/views/commentarts/_form.html.erb
<%= simple_form_for([@art, @art.commentarts.build], remote: true) do |f| %>
  <%= f.error_notification %>

  <%= f.input :content, label: "Reply" %>
	<%= f.button :submit, "Comment", class: "button" %>
	
<% end %>

app/views/commentarts/create.js.erb
$('#comments').html("<%= escape_javascript(render(:partial => @art.commentarts)) %>");