config/routes.rb
Rails.application.routes.draw do

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'pages/lyriclab'
  get 'pages/launch'
  get 'pages/how_it_works'
  get 'pages/about_us'
  get 'pages/handbook'
  get 'pages/faqs'
  get 'pages/partnerships'
  get 'pages/legal_terms'
  get 'pages/careers'
  get 'pages/events'
  get 'pages/testpage'
  get 'pages/testpage2'
  get 'pages/home'
  get 'pages/blurbarchive'

  get 'tagged' => 'posts#tagged', :as => 'tagged'

  get 'dash' => 'profiles#dash', :as => 'dash'

  devise_for :users, :controllers => { :registrations => 'user/registrations', :invitations => 'user/invitation', omniauth_callbacks: 'user/omniauth_callbacks'}

resources :archives

resources :posts do
  member do
    get "like", to: "posts#upvote"
    get "dislike", to: "posts#downvote"
  end
  
  resources :commentposts
end

  resources :campaigns do
      resources :lyrics 
      resources :arts


    get 'filter' => 'arts#tagged', :as => 'filter'
    get 'tagged' => 'lyrics#tagged', :as => 'tagged'

    
  end

resources :lyrics, only: [] do
      member do
        get "like", to: "lyrics#upvote"
        get "dislike", to: "lyrics#downvote"
      end

      resources :comments
    end



  resources :arts, only: [] do
    member do
      put "voteof1", to: "arts#voteof1"
      put "voteof2", to: "arts#voteof2"
      put "voteof3", to: "arts#voteof3"
      put "voteof4", to: "arts#voteof4"
      put "voteof5", to: "arts#voteof5"
    end

    resources :ratings
    resources :commentarts
  end

  resources :profiles do

    member do
      get :follow
      get :unfollow
    end
  
  end

  resources :products

  resources :homeinfo

  resources :videos
  resources :photos



  root 'campaigns#index'
  
  
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :large => "600x450#", :medium => "400x300#", :small => "200x150#" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	scope :approve, -> { where(:approve => true) }
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :find_video, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]
	has_scope :approve

	def index
		@videos = Video.all.order("created_at DESC")
	end

	def new
		@video = Video.new
	end

	def create
		@video = Video.new(video_params)
		@video.user_id = current_user.id

		if @video.save
			redirect_to :back
		else
			render 'new'
		end

	end

	def edit

	end

	def update
		if @video.update(video_params)
			redirect_to @video
		else
			render 'edit'
		end
	end

	def destroy
		@video.destroy
		redirect_to root_path
	end


	private

		def find_video
			@video = Video.find(params[:id])
		end

		def video_params
			params.require(:video).permit(:title, :videolink, :approve, :image)
		end
end

app/helpers/video_helper.rb
module VideoHelper

	def youtube_embed(youtube_url)
  		if youtube_url[/youtu\.be\/([^\?]*)/]
    		youtube_id = $1
  		else
		    # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
		    youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
		    youtube_id = $5
		end

  		%Q{<iframe title="YouTube video player" width="320" height="195" src="https://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
	end
end

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>

      <%= f.error_notification %>

  <% if can? :manage, :all %>
  <%= f.input :approve %>
  <% end %>

  <% if @video.approve == true %>
  <div class="approved-box">Your video has been approved.</div>

  <% if can? :manage, :all %>
  <%= f.input :title, label: "Title" %>
  <%= f.file_field :image %>
  <%= f.input :videolink, label: "Add Youtube Video Link" %>

  <%= f.button :submit, "Submit", class: "post-button" %>


  <% end %>

  <% else %>

  <%= f.input :title, label: "Title" %>

  <%= f.input :videolink, label: "Add Youtube Video Link", hint: "Input YouTube Share Link. Format: http://youtu.be/1AjULLsdp5E" %>

  <div class="form-info">
    ***All videos are reviewed before posted on profile pages.  Can take up to 48 hours for approval but usually only a few hours.

  </div>

  <%= f.button :submit, "Submit", class: "post-button" %>

  <% end %>



<% end %>

app/views/videos/edit.html.erb
<% if can? :manage, :all %>
<div class="addlyric">
<h1>Edit Video</h1>
</div>

<%= render 'form' %>

<div class="formpage-footer">
<%= link_to 'Back', profile_url(:id => current_user.username), class: "back-button" %>
</div>

<% end %>

app/views/videos/index.html.erb
<% if can? :manage, :all %>

Video Page


<% @videos.each do |video| %>
    <div class="container-post-index">
    	<%= raw(youtube_embed(video.videolink)) %>

    	<ul>
    	 <li><% if video.user.avatar.present? %>
          <%= image_tag video.user.avatar.url(:mini) %>
          <% end %>
          <% if video.user.username.present? %><%= link_to video.user.username, profile_url(:id => video.user.username) %>
          <% end %></li> 
          <li>Approval: <%= video.approve %></li>
          <li><%= link_to 'Edit', edit_video_path(video) %></li>
          <li><%= link_to 'Destroy', video, method: :delete, data: {confirm: "Are you sure?"} %></li>
      </ul>
    </div>
    	<% end %>

<% end %>

app/views/videos/new.html.erb
<div class="addlyric">
<h1>Add Video To Profile Page</h1>
</div>

<%= render 'form' %>

<div class="formpage-footer">
<%= link_to 'Back', profile_url(:id => current_user.username), class: "back-button" %>
</div>


<%= render 'layouts/footer' %>