config/routes.rb
Rails.application.routes.draw do

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'pages/lyriclab'
  get 'pages/launch'
  get 'pages/how_it_works'
  get 'pages/about_us'
  get 'pages/handbook'
  get 'pages/faqs'
  get 'pages/partnerships'
  get 'pages/legal_terms'
  get 'pages/careers'
  get 'pages/events'
  get 'pages/testpage'
  get 'pages/testpage2'
  get 'pages/home'
  get 'pages/blurbarchive'

  get 'tagged' => 'posts#tagged', :as => 'tagged'

  get 'dash' => 'profiles#dash', :as => 'dash'

  devise_for :users, :controllers => { :registrations => 'user/registrations', :invitations => 'user/invitation', omniauth_callbacks: 'user/omniauth_callbacks'}

resources :archives

resources :posts do
  member do
    get "like", to: "posts#upvote"
    get "dislike", to: "posts#downvote"
  end
  
  resources :commentposts
end

  resources :campaigns do
      resources :lyrics 
      resources :arts


    get 'filter' => 'arts#tagged', :as => 'filter'
    get 'tagged' => 'lyrics#tagged', :as => 'tagged'

    
  end

resources :lyrics, only: [] do
      member do
        get "like", to: "lyrics#upvote"
        get "dislike", to: "lyrics#downvote"
      end

      resources :comments
    end



  resources :arts, only: [] do
    member do
      put "voteof1", to: "arts#voteof1"
      put "voteof2", to: "arts#voteof2"
      put "voteof3", to: "arts#voteof3"
      put "voteof4", to: "arts#voteof4"
      put "voteof5", to: "arts#voteof5"
    end

    resources :ratings
    resources :commentarts
  end

  resources :profiles do

    member do
      get :follow
      get :unfollow
    end
  
  end

  resources :products

  resources :homeinfo

  resources :videos
  resources :photos



  root 'campaigns#index'
  
  
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	#is_impressionable :counter_cache => true, :column_name => :counter_cache, :unique => :request_hash
	belongs_to :user
	has_many :commentposts
	acts_as_taggable_on :tags
	scope :approved, -> { where(:approve => true) }

	scope :by_tags, -> tags { where(:tags => tags) }



	 TYPEOFS = %w[picture video audio]

	has_attached_file :image, :styles => { :large => "600x600#", :medium => "400x400#", :small => "200x200#" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]
	has_scope :by_tags
	before_action :tag_cloud, :only => [:index, :tagged]
	load_and_authorize_resource :only => [:show, :edit, :update, :destroy]
	#impressionist :actions => [:show,:index], :unique => [:impressionable_type, :impressionable_id, :session_hash]
	respond_to :html, :json, :js
	before_action :add_points, only: [:upvote, :downvote]
	invisible_captcha only: [:create, :update], honeypot: :subtitle

	def index

		case params[:sort_by]
	      when 'most_liked'
	        @posts = apply_scopes(Post).approved.order(:cached_votes_up => :desc).paginate(:page => params[:page], :per_page => 10)
	    when 'most_viewed'
	        @posts = apply_scopes(Post).approved.order(:counter_cache => :desc).paginate(:page => params[:page], :per_page => 10)
	      when 'most_recent'
	        @posts = apply_scopes(Post).approved.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
	      else
	        @posts = apply_scopes(Post).approved.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
	    end

	end

	def show
		@commentposts = Commentpost.where(post_id: @post)

		@random_posts = Post.where.not(id: @post).order("RANDOM()").take(5)

		if @post == Post.last
			@next_post = Post.order(id: :asc).first
		else
			@next_post = Post.where("id > ?", @post).order(id: :asc).first
		end

		if @post == Post.first
			@previous_post = Post.order(id: :asc).last
		else
			@previous_post = Post.where("id < ?", @post).order(id: :desc).first
		end
		
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def upvote
		@post.upvote_by current_user

		respond_to do |format|
    		format.html {redirect_to :back }
    		format.json { render json: { count: @post.cached_votes_up, count2: @post.cached_votes_down }}
    		format.js { render :layout => false }
    	end

	end

	def downvote
		@post.downvote_by current_user
		
		respond_to do |format|
    		format.html {redirect_to :back }
    		format.json { render json: {  count: @post.cached_votes_up, count2: @post.cached_votes_down } }
    		format.js { render :layout => false }
    	end
	end

	def add_points
		if user_signed_in?
		unless (current_user.voted_for? @post)

          @current_user.add_points(1, category: 'blog')
        
      	end
      end
	end

	def tagged

  		if params[:tag].present? 
    		@posts = Post.tagged_with(params[:tag]).order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  		else 
    		@posts = apply_scopes(Post).all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)

  		end  
	end

	def tag_cloud
		
   		 @tags = Post.tag_counts_on(:tags)
  	end

	



private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :description, :link, :typeof, :approve, :image, :videolink, :audiolink, :tag_list)
	end

end

app/helpers/posts_helper.rb
module PostsHelper

	 def youtube_embed(youtube_url)
  		if youtube_url[/youtu\.be\/([^\?]*)/]
    		youtube_id = $1
  		else
		    # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
		    youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
		    youtube_id = $5
		end

  		%Q{<iframe title="YouTube video player" width="640" height="390" src="https://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
	end
	
end

app/views/posts/edit.html.erb
<div class="addlyric">
<h1>Edit post</h1>
</div>

<%= render 'form' %>

<div class="formpage-footer">
<%= link_to 'Blog', posts_path, class: "back-button" %>
</div>


<%= render 'layouts/footer' %>

app/views/posts/index.html.erb
<section class="main-section">

<section class="post-section">

<div class="works-top" id="works-exp2">
  <div class="how-campaign">
  <h2>"Inspire Passion" Blog</h2>
  <p>A community blog showcasing the work and journey of creative individuals and the cultures of local communities around the world.</p>

  </div>

  <div class="how-box2">

  <%= link_to 'Submit Post', new_post_path , :class => "" %>

    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Sort
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><%= link_to 'Most Liked', :controller => 'posts', :sort_by => 'most_liked' %></li>
        <li role="presentation"><%= link_to 'Most Viewed', :controller => 'posts', :sort_by => 'most_viewed' %></li>
        <li role="presentation"><%= link_to 'Most Recent', :controller => 'posts', :sort_by => 'most_recent' %></li>
      </ul>
    </div>


        <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Filter
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

         <% @tags.each do |tag| %>
              <% if tag.taggings_count > 4 %>
              <li role="presentation"><%= link_to tag.name, tagged_url(:tag => tag.name) %></li>
              <% end %>
          
            <% end %>
      </ul>
    </div>


  </div>

  <div class="how-box2-mobile">

    <%= link_to new_post_path do %>
  
      <span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"></span>
    <% end %>

    <div class="clear"></div>

    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        <span class="glyphicon glyphicon glyphicon-sort" aria-hidden="true"></span>
        <span class="caret"></span>
      </button>

       <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><%= link_to 'Most Liked', :controller => 'posts', :sort_by => 'most_liked' %></li>
        <li role="presentation"><%= link_to 'Most Viewed', :controller => 'posts', :sort_by => 'most_viewed' %></li>
        <li role="presentation"><%= link_to 'Most Recent', :controller => 'posts', :sort_by => 'most_recent' %></li>
      </ul>
    </div>

    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        <span class="glyphicon glyphicon glyphicon-filter" aria-hidden="true"></span>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

         <% @tags.each do |tag| %>
              <% if tag.taggings_count > 4 %>
              <li role="presentation"><%= link_to tag.name, tagged_url(:tag => tag.name) %></li>
              <% end %>
          
            <% end %>
      </ul>
    </div>



  </div>


  </div>


  <div id="posts">
    <% @posts.each do |post| %>
    <div class="container-post-index">

       <% unless post.videolink.nil? || post.videolink.empty? %>
			<% if post.typeof == 'video' %>
				<div class="video-box">
				<p><%= raw(youtube_embed(post.videolink)) %></p>
				</div>
			<% end %>
		<% end %>

		<% unless post.audiolink.nil? || post.audiolink.empty? %>
			<% if post.typeof == 'audio' %>
				<p><%= raw(post.audiolink) %></p>
				<% end %>
		<% end %>

		<% unless post.image.nil? || post.image.blank? %>
			<% if post.typeof == 'picture' %>
        <%= link_to post_path(post) do %>
				  <%= image_tag post.image.url(:medium) %>
        <% end %>
				<% end %>
		<% end %>

    <% if post.title.present? %> 
        <div class="post-title"><%= link_to Obscenity.replacement(:nonconsonants).sanitize(post.title), post_path(post) %></div>
    <% end %>

        <ul>
          <% if user_signed_in? %>
          <li><span class="updown-button"><span class="up <%= post.id %>"><%= post.get_upvotes.size %> </span>
          <%= link_to like_post_path(post), class: ['voteup', post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= post.id %>"><%= post.get_downvotes.size %></span>
          <%= link_to dislike_post_path(post), class: ['votedown', post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>

          </li>

          <% else %>

          <li><span class="updown-button"><span class="up <%= post.id %>"><%= post.get_upvotes.size %> </span>
          <%= link_to_if user_signed_in?, like_post_path(post), class: ['voteup', post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= post.id %>"><%= post.get_downvotes.size %></span>
          <%= link_to_if user_signed_in?, dislike_post_path(post), class: ['votedown', post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>
        
          <span type="button" data-toggle="tooltip" data-placement="top" title="Sign In To Vote" class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
          </li>


          <% end %>


          <% if false %>
          <% if can? :manage, :all %>
        <li><%= post.impressionist_count(:filter=>:session_hash) %> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></li>
        <% end %>
        <% end %>



              <script>

                $('.voteup' + '.<%= post.id %>')
              .on('ajax:success', function (e, data, status, xhr) { 
                $('.up' + '.<%= post.id %>').html(data.count);
                $('.down' + '.<%= post.id %>').html(data.count2);
              });

                </script>

                  <script>

                $('.votedown' + '.<%= post.id %>')
              .on('ajax:success', function (e, data, status, xhr) { 
                
                $('.down' + '.<%= post.id %>').html(data.count2);
                $('.up' + '.<%= post.id %>').html(data.count);
              });

                </script>

        <li><%= post.commentposts.count %> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></li>
        <li><% if post.user.avatar.present? %>
          <%= image_tag post.user.avatar.url(:mini) %>
          <% end %>
          <% if post.user.username.present? %><%= link_to post.user.username, profile_url(:id => post.user.username) %>
          <% end %></li> 

        </ul>
        <br />
        <ul class="tag-list">
        <li><% post.tags.any? %>
          <% post.tags.each do |tag| %>
          <%= link_to tag.name, tagged_url(:tag => tag.name) %>
          <% end %></li>
        </ul>
     
      
      </div>
    <% end %>

    <div class="back-top" title="Top of Page"> <a href="#top" onclick="return false;"><i class="glyphicon glyphicon-chevron-up"></i></a></div> 
  </div>

   <br>
    <div class="center">
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    </div>

  <%= render 'layouts/footer' %>

</section>

      <section class="home-info">


        <div class="results"></div>
          

      </section>


</section>



<script>
$(function(){


    // Enabling Popover Example 2 - JS (hidden content and title capturing)
    $(".popoverExampleTwo").popover({
        html : true, 
        content: function() {
          return $('.popoverExampleTwoHiddenContent').html();
        },
        title: function() {
          return $('.popoverExampleTwoHiddenTitle').html();
        }
    });
});

</script>

<script>
// fade in #back-top
$(function () {
    $(window).scroll(function () {
        if ($(this).scrollTop() > 300) {
            $('.back-top').fadeIn();
        } else {
            $('.back-top').fadeOut();
        }
    });

    // scroll body to 0px on click
    $('.back-top').click(function () {
        $('body,html').animate({
            scrollTop: 0
        }, 1600);
        return false;
    });
});
</script>

<script>
$(window).scroll(function () {
    var winTop = $(this).scrollTop(),
        winBottom = winTop + $(this).height(),
        left = $('.home-info'),
        leftBottom = left.height(),
        right = $('.post-section'),
        rightBottom = right.height();
    //when the user reached the bottom of '#leftShort' set its position to fixed 
    //to prevent it from moving on scroll 
    if (rightBottom <= leftBottom){


    } else{

          if (winBottom >= leftBottom) {
        left.css({
            'position': 'fixed',
            'bottom': '0px',
            
        });
    } else {
        //when the user scrolls back up revert its position to relative
        // to make it move up together with '#rightLong'
        left.css({
            'position': 'relative',
            'bottom': 'auto'

        });
    }

    }


});

</script>

<script>

  $('.results').html("<%= j render(:partial => 'homeinfo/index') %>")

</script>

app/views/posts/new.html.erb
<div class="addlyric">
<h1>Add Post To Community Blog</h1>
</div>

<%= render 'form' %>

<div class="formpage-footer">
<%= link_to 'Blog', posts_path, class: "back-button" %>
</div>


<%= render 'layouts/footer' %>

app/views/posts/show.html.erb
<section class="post-section">
    <div class="stepbackward">
    			<%= link_to post_path(@previous_post) do %>
    				<span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
    			<% end %>
    		</div>
    		<div class="stepforward">
    			<%= link_to post_path(@next_post) do %>
    				<span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span>
    			<% end %>
    			</div>
    <div class="container-show">
    	
    	<div class="container-post">

        <% if @post.title.present? %>
    		<h1><%= Obscenity.replacement(:nonconsonants).sanitize(@post.title) %></h1>
        <% end %>
    	
    		<% unless @post.videolink.nil? || @post.videolink.empty? %>
    			<% if @post.typeof == 'video' %>
    				<p><%= raw(youtube_embed(@post.videolink)) %></p>
    			<% end %>
    		<% end %>

    		<% unless @post.audiolink.nil? || @post.audiolink.empty? %>
    			<% if @post.typeof == 'audio' %>
    				<p><%= raw(@post.audiolink) %></p>
    				<% end %>
    		<% end %>

    		<% unless @post.image.nil? || @post.image.blank? %>
    			<% if @post.typeof == 'picture' %>
    				<%= image_tag @post.image.url(:medium) %>
    				<% end %>
    		<% end %>



    	</div>
    	
    <div class="container-post-extra">

    	 <ul>

        <% if user_signed_in? %>
          <li><span class="updown-button"><span class="up <%= @post.id %>"><%= @post.get_upvotes.size %> </span>
          <%= link_to like_post_path(@post), class: ['voteup', @post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= @post.id %>"><%= @post.get_downvotes.size %></span>
          <%= link_to dislike_post_path(@post), class: ['votedown', @post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>

          </li>

          <% else %>

          <li><span class="updown-button"><span class="up <%= @post.id %>"><%= @post.get_upvotes.size %> </span>
          <%= link_to_if user_signed_in?, like_post_path(@post), class: ['voteup', @post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= @post.id %>"><%= @post.get_downvotes.size %></span>
          <%= link_to_if user_signed_in?, dislike_post_path(@post), class: ['votedown', @post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>
        
          <span type="button" data-toggle="tooltip" data-placement="top" title="Sign In To Vote" class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
          </li>


          <% end %>
          </ul>

          <ul>
            <% if false %>
            <li><%= @post.impressionist_count(:filter=>:session_hash) %> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></li>
            <% end %>
             

          <li><%= @post.commentposts.count %> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></li>
           
            
            </ul>
         
            <% unless @post.tags.nil? || @post.tags.empty? %>
            <ul>
    		<li>
      			<% @post.tags.each do |tag| %>
      				<%= link_to tag.name, tagged_url(:tag => tag.name) %>
      			<% end %>
    			</li>
    		</ul>
    		<% end %>

        <ul>

          <li><strong>Posted By:</strong> <% if @post.user.avatar.present? %>
            <%= image_tag @post.user.avatar.url(:mini) %>
            <% end %> 
            <% if @post.user.username.present? %>
            <%= link_to @post.user.username, profile_url(:id => @post.user.username) %>
            <% end %></li>
          
        </ul>

    		       <div class="artist-info">
    		    <ul>
    			 <% if @post.link.present? %>
    				<li><%= link_to 'More Info', @post.link %></li>
            <% end %>
    			</ul>

            </div>

            <ul>
            	<li>
    			<% if can? :manage, :all %>

    			<span class="adminonly">Approval: <%= @post.approve %></span>
    			<% end %>

    		</li>
            		<li><% if can? :update, @post %>
    		<%= link_to 'Edit', edit_post_path(@post) %> | 
    		<% end %>
    		<% if can? :destroy, @post %>
    		<%= link_to 'Destroy', [@post], method: :delete, data: {confirm: "Are you sure?" } %>
    		<% end %></li>
    		

            </ul>
     
        </div>

       <% unless @post.description.nil? || @post.description.empty? %>
    	<div class="container-post-desc">
    		 
    		<%= simple_format(@post.description) %>
    	</div>
    	<% end %>
    		
    	<div class="container-comment">
    	<h2 class="comment_count">
    		<%= pluralize(@post.commentposts.count, "Response") %></h2>
    		<hr />
    	    <div id="comments">
         <%= render @post.commentposts %>
       </div>

    	<%= render 'commentposts/form' %>
    </div>
    </div>



  <div id="posts">
    <% @random_posts.each do |random_post| %>
    <div class="container-post-index">

       <% unless random_post.videolink.nil? || random_post.videolink.empty? %>
      <% if random_post.typeof == 'video' %>
        <div class="video-box">
        <p><%= raw(youtube_embed(random_post.videolink)) %></p>
        </div>
      <% end %>
    <% end %>

    <% unless random_post.audiolink.nil? || random_post.audiolink.empty? %>
      <% if random_post.typeof == 'audio' %>
        <p><%= raw(random_post.audiolink) %></p>
        <% end %>
    <% end %>

    <% unless random_post.image.nil? || random_post.image.blank? %>
      <% if random_post.typeof == 'picture' %>
        <%= link_to post_path(random_post) do %>
          <%= image_tag random_post.image.url(:medium) %>
        <% end %>
        <% end %>
    <% end %>

    <% if random_post.title.present? %> 
        <div class="post-title"><%= link_to Obscenity.replacement(:nonconsonants).sanitize(random_post.title), post_path(random_post) %></div>
    <% end %>

        <ul>
          <% if user_signed_in? %>
          <li><span class="updown-button"><span class="up <%= random_post.id %>"><%= random_post.get_upvotes.size %> </span>
          <%= link_to like_post_path(random_post), class: ['voteup', random_post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= random_post.id %>"><%= random_post.get_downvotes.size %></span>
          <%= link_to dislike_post_path(random_post), class: ['votedown', random_post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>

          </li>

          <% else %>

          <li><span class="updown-button"><span class="up <%= random_post.id %>"><%= random_post.get_upvotes.size %> </span>
          <%= link_to_if user_signed_in?, like_post_path(random_post), class: ['voteup', random_post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
            <% end %>
          </span>
        </li>
        <li>
            <span class="updown-button"><span class="down <%= random_post.id %>"><%= random_post.get_downvotes.size %></span>
          <%= link_to_if user_signed_in?, dislike_post_path(random_post), class: ['votedown', random_post.id], remote: true, data: { type: :json }, method: :get do %>
          <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <% end %>
          </span>
        
          <span type="button" data-toggle="tooltip" data-placement="top" title="Sign In To Vote" class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
          </li>


          <% end %>



          <% if false %>
        <li><%= random_post.impressionist_count(:filter=>:session_hash) %> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></li>
        <% end %>



              <script>

                $('.voteup' + '.<%= random_post.id %>')
              .on('ajax:success', function (e, data, status, xhr) { 
                $('.up' + '.<%= random_post.id %>').html(data.count);
                $('.down' + '.<%= random_post.id %>').html(data.count2);
              });

                </script>

                  <script>

                $('.votedown' + '.<%= random_post.id %>')
              .on('ajax:success', function (e, data, status, xhr) { 
                
                $('.down' + '.<%= random_post.id %>').html(data.count2);
                $('.up' + '.<%= random_post.id %>').html(data.count);
              });

                </script>

        <li><%= random_post.commentposts.count %> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></li>
        <li><% if random_post.user.avatar.present? %>
          <%= image_tag random_post.user.avatar.url(:mini) %>
          <% end %>
          <% if random_post.user.username.present? %><%= link_to random_post.user.username, profile_url(:id => random_post.user.username) %>
          <% end %></li> 

        </ul>
        <br />
        <ul class="tag-list">
        <li><% random_post.tags.any? %>
          <% random_post.tags.each do |tag| %>
          <%= link_to tag.name, tagged_url(:tag => tag.name) %>
          <% end %></li>
        </ul>
     
      
      </div>
    <% end %>

    <div class="back-top" title="Top of Page"> <a href="#top" onclick="return false;"><i class="glyphicon glyphicon-chevron-up"></i></a></div> 
  </div>

  <%= render 'layouts/footer' %>

</section>



<section class="home-info">


  <div class="results"></div>
    

</section>



<script>
$(function(){


    // Enabling Popover Example 2 - JS (hidden content and title capturing)
    $(".popoverExampleTwo").popover({
        html : true, 
        content: function() {
          return $('.popoverExampleTwoHiddenContent').html();
        },
        title: function() {
          return $('.popoverExampleTwoHiddenTitle').html();
        }
    });

     // Enabling Popover Example 2 - JS (hidden content and title capturing)
    $(".popoverExampleThree").popover({
        html : true, 
        content: function() {
          return $('.popoverExampleThreeHiddenContent').html();
        },
        title: function() {
          return $('.popoverExampleThreeHiddenTitle').html();
        }
    });

});

</script>

<script>
$(window).scroll(function () {
    var winTop = $(this).scrollTop(),
        winBottom = winTop + $(this).height(),
        left = $('.home-info'),
        leftBottom = left.height(),
        right = $('.post-section'),
        rightBottom = right.height();
    //when the user reached the bottom of '#leftShort' set its position to fixed 
    //to prevent it from moving on scroll 
    if (rightBottom <= leftBottom){


    } else{

          if (winBottom >= leftBottom) {
        left.css({
            'position': 'fixed',
            'bottom': '0px',
            
        });
    } else {
        //when the user scrolls back up revert its position to relative
        // to make it move up together with '#rightLong'
        left.css({
            'position': 'relative',
            'bottom': 'auto'

        });
    }

    }


});

</script>

  <script>

    $('.voteup' + '.<%= @post.id %>')
  .on('ajax:success', function (e, data, status, xhr) { 
    $('.up' + '.<%= @post.id %>').html(data.count);
    $('.down' + '.<%= @post.id %>').html(data.count2);
  });

    </script>

      <script>

    $('.votedown' + '.<%= @post.id %>')
  .on('ajax:success', function (e, data, status, xhr) { 
    
    $('.down' + '.<%= @post.id %>').html(data.count2);
    $('.up' + '.<%= @post.id %>').html(data.count);
  });

    </script>

<script>

  $('.results').html("<%= j render(:partial => 'homeinfo/index') %>")

</script>